In [6]:
# Create a DataFrame based on pseudorandom numbers and with enough rows that only the head and tail are shown

import datetime as dt
import xlwings as xw
import pandas as pd
import numpy as np

df = pd.DataFrame(data=np.random.randn(100, 5),
                  columns=[f"Trial {i}" for i in range(1, 6)])
df

     Trial 1   Trial 2   Trial 3   Trial 4   Trial 5
0   0.349909 -0.788140 -1.185509  0.490285  2.112801
1   0.285749 -1.916104 -0.933683  0.378872 -1.526691
2   0.442065 -1.020329  0.176199 -1.921251 -0.970872
3  -0.275909  0.395934 -0.194986 -0.584822  0.928800
4   0.375529  0.012345  1.033753  0.617980  1.418155
..       ...       ...       ...       ...       ...
95  1.655976 -0.484543  1.656219  0.339239 -0.950001
96 -1.782084  0.663854  2.425526  0.707118  1.418481
97  0.689089 -0.167542 -1.931577  0.593986 -0.602343
98 -0.118374 -0.342618  0.131793 -1.395940  0.633448
99  0.500705  0.647949 -0.079219  0.703663 -0.770137

[100 rows x 5 columns]

In [7]:
# View the DataFrame in Excel
xw.view(df)