In [1]:
# Create a DataFrame based on pseudorandom numbers and with enough rows that only the head and tail are shown

import datetime as dt
import xlwings as xw
import pandas as pd
import numpy as np

df = pd.DataFrame(data=np.random.randn(100, 5),
                  columns=[f"Trial {i}" for i in range(1, 6)])
df

     Trial 1   Trial 2   Trial 3   Trial 4   Trial 5
0   0.966640  0.769323 -0.839546 -1.322940  0.242346
1  -0.354727  0.712155  1.045536 -0.024003  0.704983
2  -0.409219 -1.281956  1.478649  0.459148 -1.377026
3   0.099168 -0.027902 -0.138419  0.414208  0.425967
4  -0.505629 -0.929166 -0.243857 -0.690529 -0.322825
..       ...       ...       ...       ...       ...
95 -0.217405  1.077102  1.034328 -0.066220 -0.097499
96  0.381129  1.149244  0.162719  0.631153 -0.742012
97  1.396311  0.485406  0.429738  0.442831 -0.657099
98 -0.832715  1.650247 -0.078562 -0.403796  0.826505
99  0.870063 -1.060724  0.394374  0.333635  1.931462

[100 rows x 5 columns]

In [2]:
# In [3]: # View the DataFrame in Excel

xw.view(df)