In [2]:
# Create a DataFrame based on pseudorandom numbers and with enough rows that only the head and tail are shown

import datetime as dt
import xlwings as xw
import pandas as pd
import numpy as np

df = pd.DataFrame(data=np.random.randn(100, 5),
                  columns=[f"Trial {i}" for i in range(1, 6)])

# View the DataFrame in Excel
xw.view(df)

df

     Trial 1   Trial 2   Trial 3   Trial 4   Trial 5
0   0.161443 -0.567396 -0.571283 -1.901456 -0.381809
1  -1.326368 -1.618374 -0.181715 -0.646561 -0.625993
2  -0.999312 -0.216017 -1.448401 -0.260433  0.636037
3   1.265485 -0.959496  0.665519  1.680771  0.498494
4   0.829938  1.012131  2.140089  0.015233  0.520558
..       ...       ...       ...       ...       ...
95 -1.268369 -0.861140  2.082911 -0.217972  0.868533
96 -0.195129  1.053729 -0.260768 -0.256485  0.465463
97  0.807764 -1.196663 -0.611600  2.171787 -0.274726
98  1.836014  0.554125 -1.072857  0.878396  2.568366
99 -0.670239  0.281116 -1.725680 -0.195027  0.581192

[100 rows x 5 columns]