In [7]:
# In [1]: # First, let's import the packages that we'll use in this chapter

import datetime as dt
import xlwings as xw
import pandas as pd
import numpy as np

In [8]:
# In [2]: # Let's create a DataFrame based on pseudorandom numbers and
        # with enough rows that only the head and tail are shown

df = pd.DataFrame(data=np.random.randn(100, 5),
                  columns=[f"Trial {i}" for i in range(1, 6)])
df

     Trial 1   Trial 2   Trial 3   Trial 4   Trial 5
0   0.252873 -0.969863  1.287498 -0.644374  0.273195
1   0.788589 -1.006518  1.588722 -0.965793  0.351718
2  -0.554614  1.151973 -0.719271  0.660819 -0.325689
3  -0.799519 -1.239926  1.125713 -0.796306 -0.054374
4  -0.344497  1.155638 -0.287050  3.135628 -0.301208
..       ...       ...       ...       ...       ...
95 -1.884208  0.123657  0.721544 -0.289974 -0.053299
96  0.244572 -1.606666  0.190045  0.571467  1.088947
97  1.589570 -1.184227  2.119080 -0.960769  0.455535
98 -1.336303  0.111207  0.326630 -0.625007 -1.797154
99 -2.114395 -1.781629 -1.383828 -0.390271  1.128628

[100 rows x 5 columns]

In [9]:
# In [3]: # View the DataFrame in Excel

xw.view(df)